[DISE-6200] Add screen captures to get started doc
AdobeDocs/cis-photoshop-api-docs pull request #86
Opened 2022-07-14 22:04 UTC by dipu2022

JIRA: https://jira.corp.adobe.com/browse/DISE-6200

2022-07-14 22:32 UTC, khound commented
Looks good to me. Let @archyposada review once.

2022-07-15 16:59 UTC, archyposada requested changes
Looks good! Would you mind changing the first sentence in the index file. I left a comment on it.

2022-07-15 16:59 UTC, archyposada commented on src/pages/getting-started/index.md
>  Here are the steps to start with our API
"Here are the steps top get started with the Ps API." 

Lets change this sentence for better grammar and clarity.

2022-07-15 17:05 UTC, archyposada approved these changes

2022-07-15 17:06 UTC, merged